apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: P1
    access: proxy
    url: postgres:5432
    user: iot_user
    secureJsonData:
      password: iot_password
    jsonData:
      database: iot_telemetry
      sslmode: disable
      postgresVersion: 15
      timescaledb: false
    isDefault: true
